#!/bin/sh
# RAUC post-install handler for NanoPi Zero2
#
# This handler is called after RAUC installs an update to a slot.
# It performs two critical tasks:
#   1. Updates extlinux.conf to point to the correct rootfs partition
#   2. Copies device identity from /persist to the new slot
#
# Device identity includes:
#   - muid.data (probe UUID)
#   - machine-id
#   - SSH host keys
#
# NOTE: RAUC environment variables (RAUC_SLOT_NAME, etc.) are NOT reliably
# set when this handler is called. We detect the target slot independently.

# Use full paths for commands (RAUC may not have full PATH)
PARTED="/usr/sbin/parted"
LOGGER="/usr/bin/logger"
GREP="/bin/grep"
DISK="/dev/mmcblk2"
ROOTFS_A_PARTNUM=3
ROOTFS_B_PARTNUM=4
PERSIST_PARTNUM=5
PERSIST_DIR="/persist/rauc"
IDENTITY_DIR="device-identity"

# Ensure /persist is remounted ro on exit (safety net for pre-install rw remount)
cleanup_persist() {
    mount -o remount,ro /persist 2>/dev/null || true
}
trap cleanup_persist EXIT

log() {
    echo "[post-install] $*" >&2
    $LOGGER -t rauc-post-install "$*" 2>/dev/null || true
}

error() {
    log "ERROR: $*"
    exit 1
}

log "Post-install handler started"

# Detect current slot from kernel cmdline (most reliable method)
CURRENT_SLOT=$($GREP -o 'rauc\.slot=[ab]' /proc/cmdline 2>/dev/null | cut -d= -f2)

# Fallback: check which partition has legacy_boot flag
if [ -z "$CURRENT_SLOT" ]; then
    log "No rauc.slot in cmdline, checking GPT flags"
    if $PARTED -s "$DISK" print 2>/dev/null | $GREP -E "^\s*${ROOTFS_A_PARTNUM}\s" | $GREP -q "legacy_boot"; then
        CURRENT_SLOT="a"
    else
        CURRENT_SLOT="b"
    fi
fi

# Target is the opposite of current (RAUC always installs to inactive slot)
if [ "$CURRENT_SLOT" = "a" ]; then
    TARGET_SLOT="b"
    TARGET_DEVICE="/dev/mmcblk2p${ROOTFS_B_PARTNUM}"
else
    TARGET_SLOT="a"
    TARGET_DEVICE="/dev/mmcblk2p${ROOTFS_A_PARTNUM}"
fi

PERSIST_DEVICE="/dev/mmcblk2p${PERSIST_PARTNUM}"

log "Current slot: $CURRENT_SLOT, Target slot: $TARGET_SLOT"
log "Target device: $TARGET_DEVICE"

# Use /tmp for mount points (rootfs is read-only, /tmp is tmpfs)
TARGET_MOUNT="/tmp/rauc-target"
PERSIST_MOUNT="/tmp/rauc-persist"
mkdir -p "$TARGET_MOUNT" "$PERSIST_MOUNT"

# =============================================================================
# Mount target slot and persist partition
# =============================================================================
if ! mount "$TARGET_DEVICE" "$TARGET_MOUNT"; then
    error "Could not mount $TARGET_DEVICE - post-install cannot proceed"
fi
log "Mounted $TARGET_DEVICE to $TARGET_MOUNT"

# =============================================================================
# STEP 1: Update extlinux.conf for the new slot
# =============================================================================
if [ -d "$TARGET_MOUNT/boot/extlinux" ]; then
    {
        echo "# Extlinux configuration for NanoPi Zero2 (RAUC A/B Boot - Slot ${TARGET_SLOT})"
        echo "# Auto-generated by RAUC post-install handler"
        echo ""
        echo "default Yocto Linux Slot ${TARGET_SLOT}"
        echo "timeout 3"
        echo ""
        echo "label Yocto Linux Slot ${TARGET_SLOT}"
        echo "    kernel /boot/Image"
        echo "    fdt /boot/rk3528-nanopi-rev01.dtb"
        echo "    append root=PARTLABEL=rootfs-${TARGET_SLOT} rauc.slot=${TARGET_SLOT} rootwait rootfstype=ext4 console=ttyFIQ0,1500000n8 earlycon=uart8250,mmio32,0xff9f0000"
    } > "$TARGET_MOUNT/boot/extlinux/extlinux.conf"

    log "Updated extlinux.conf for slot $TARGET_SLOT"
else
    log "Warning: boot/extlinux directory not found in target slot"
fi

# =============================================================================
# STEP 2: Copy device identity from persist partition to new slot
# =============================================================================
if mount "$PERSIST_DEVICE" "$PERSIST_MOUNT" 2>/dev/null; then
    log "Mounted persist partition, copying device identity..."

    # Copy muid.data (probe UUID)
    if [ -f "$PERSIST_MOUNT/${IDENTITY_DIR}/muid.data" ]; then
        cp "$PERSIST_MOUNT/${IDENTITY_DIR}/muid.data" "$TARGET_MOUNT/etc/muid.data"
        log "Copied muid.data to new slot"
    else
        log "Warning: muid.data not found on persist partition"
    fi

    # Copy machine-id
    if [ -f "$PERSIST_MOUNT/${IDENTITY_DIR}/machine-id" ]; then
        cp "$PERSIST_MOUNT/${IDENTITY_DIR}/machine-id" "$TARGET_MOUNT/etc/machine-id"
        log "Copied machine-id to new slot"
    else
        log "Warning: machine-id not found on persist partition"
    fi

    # Copy SSH host keys
    if [ -d "$PERSIST_MOUNT/${IDENTITY_DIR}/ssh" ]; then
        mkdir -p "$TARGET_MOUNT/etc/ssh/keys"
        cp "$PERSIST_MOUNT/${IDENTITY_DIR}/ssh/"* "$TARGET_MOUNT/etc/ssh/keys/" 2>/dev/null || true
        # Update sshd config to use keys from /etc/ssh/keys/
        if [ -f "$TARGET_MOUNT/etc/ssh/sshd_config_readonly" ]; then
            sed -i 's|/var/run/ssh/|/etc/ssh/keys/|g' "$TARGET_MOUNT/etc/ssh/sshd_config_readonly"
        fi
        log "Copied SSH keys to new slot"
    else
        log "Warning: SSH keys not found on persist partition"
    fi

    umount "$PERSIST_MOUNT" || log "Warning: Failed to unmount persist"
else
    log "Warning: Could not mount persist partition - identity not copied"
fi

# =============================================================================
# Cleanup
# =============================================================================
sync
umount "$TARGET_MOUNT" || log "Warning: Failed to unmount $TARGET_MOUNT"
rmdir "$TARGET_MOUNT" "$PERSIST_MOUNT" 2>/dev/null || true

# Write slot indicator to persist partition (if already mounted via fstab)
if [ -d "/persist" ]; then
    # /persist is mounted read-only by default, remount temporarily
    mount -o remount,rw /persist 2>/dev/null || true
    mkdir -p "${PERSIST_DIR}"
    echo "rauc_slot=${TARGET_SLOT}" > "${PERSIST_DIR}/slot.tmp" && \
        mv "${PERSIST_DIR}/slot.tmp" "${PERSIST_DIR}/slot"
    log "Wrote slot indicator to ${PERSIST_DIR}/slot"

    # Reset boot counter and state for target slot (fresh update gets fresh attempts)
    echo "0" > "${PERSIST_DIR}/boot-count-${TARGET_SLOT}.tmp" && \
        mv "${PERSIST_DIR}/boot-count-${TARGET_SLOT}.tmp" "${PERSIST_DIR}/boot-count-${TARGET_SLOT}"
    echo "good" > "${PERSIST_DIR}/state-${TARGET_SLOT}.tmp" && \
        mv "${PERSIST_DIR}/state-${TARGET_SLOT}.tmp" "${PERSIST_DIR}/state-${TARGET_SLOT}"
    log "Reset boot counter and state for slot $TARGET_SLOT"

    # Remount back to read-only (also handled by EXIT trap as safety net)
    mount -o remount,ro /persist 2>/dev/null || true
fi

log "Post-install handler completed successfully for slot $TARGET_SLOT"
exit 0
