# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "nanopi-zero2"
BBFILE_PATTERN_nanopi-zero2 = "^${LAYERDIR}/"
BBFILE_PRIORITY_nanopi-zero2 = "10"

LAYERDEPENDS_nanopi-zero2 = "core rockchip"
LAYERSERIES_COMPAT_nanopi-zero2 = "scarthgap styhead"